version: 3

groups:
  code:
    reviewers:
      users:
      - ajayojha
      - rxwebteam
      - rxcontributorone
    reviews:
      required: 1  # number of approvals required from this group
      request: 1  # number of review requests sent at a time
      request_order: random  # "random" or "given"
  reactive_form_validators:
    conditions:
      files:
        - "packages/reactive-form-validators/*"
      users:
        - ajayojha
  reactive_form_validators_testing:
      conditions:
        files:
          - "test/reactive-form-validators/*"
      users:
        - ajayojha
  docs/reactive_form_validators:
      conditions:
        files:
          include:
            - "docs/reactive_form_validators/*"
      users:
        - rxcontributorone
  docs/reactive_form_validators:
      conditions:
        files:
          include:
            - "rxweb.io/*"
      users:
        - rxwebteam
