version: 3

groups:
  code:
    reviewers:
      users:
      - ajayojha
      - rxwebteam
      - rxcontributorone
    reviews:
      required: 1  # number of approvals required from this group
      request: 1  # number of review requests sent at a time
      request_order: random  # "random" or "given"
  reactive_form_validators:
    conditions:
    - "'packages/reactive-form-validators/*' in files"
    reviewers:
      users:
      - ajayojha
  reactive_form_validators_testing:
    conditions:
    - "'test/reactive-form-validators/*' in files"
    reviewers:
      users:
      - ajayojha
  docs/reactive_form_validators:
    conditions:
    - "'docs/reactive_form_validators/*' in files"
    reviewers:
      users:
      - rxcontributorone
      - ajayojha
  docs/reactive_form_validators:
    conditions:
    - "'rxweb.io/*' in files"
    reviewers:
      users:
      - rxwebteam
      - ajayojha
