version: 3

groups:
  all:
    users: all
    required: 1
    rejection_value: -999
    author_approval:
      auto: false
      ignored: true
    files:
      include:
        - "*"
  reactive_form_validators:
      conditions:
        files:
          - "packages/reactive-form-validators/*"
      users:
        - ajayojha
  reactive_form_validators_testing:
      conditions:
        files:
          - "test/reactive-form-validators/*"
      users:
        - ajayojha
  docs/reactive_form_validators:
      conditions:
        files:
          include:
            - "docs/reactive_form_validators"
      users:
        - ajayojha
