version: 3

groups:
  code:
    reviewers:
      users:
      - ajayojha
      - rxwebteam
      - rxcontributorone
    reviews:
      required: 1  # number of approvals required from this group
      request: 1  # number of review requests sent at a time
      request_order: random  # "random" or "given"
  reactive_form_validators:
    conditions:
    "packages/reactive-form-validators/*"
    users:
    ajayojha
  reactive_form_validators_testing:
      conditions:
      "test/reactive-form-validators/*"
      users:
      ajayojha
  docs/reactive_form_validators:
      conditions:
      "docs/reactive_form_validators/*"
      users:
      rxcontributorone
  docs/reactive_form_validators:
      conditions:
      "rxweb.io/*"
      users:
      rxwebteam
