language: node_js
sudo: required
node_js:
  - '10.9.0'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
     - ./node_modules
     - ./.chrome/chromium

branches:
  only:
  - master
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
   - "sudo chown root /opt/google/chrome/chrome-sandbox"
   - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script:
  - node_modules/.bin/ng test --watch=false
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
