language: node_js
sudo: false
node_js:
  - '10.9.0'
branches:
  - master
cache:
  yarn: true
  directories:
     - ./node_modules
install:
  - npm install
script:
  - ng test
  - codecov -f coverage/*.json
